import { ArrowRight, Users, Brain, Shield, Sparkles, CheckCircle2, Heart, GitBranch } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Link } from "react-router-dom";
import measureLogo from "@/assets/measure-logo.png";

const CommunityApproach = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#000860] via-[#253B96] to-[#000860]">
      {/* Header */}
      <header className="container mx-auto px-6 py-8">
        <div className="flex items-center justify-between">
          <Link to="/" className="flex items-center gap-3">
            <img src={measureLogo} alt="MEASURE" className="h-10" />
          </Link>
          <Link to="/auth">
            <Button variant="outline" className="border-white/30 text-white hover:bg-white/10">
              Get Started
            </Button>
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 text-center">
        <div className="inline-flex items-center gap-2 bg-[#E8973E]/20 text-[#F9D448] px-4 py-2 rounded-full text-sm font-medium mb-6">
          <Sparkles className="h-4 w-4" />
          A New Paradigm in AI Bias Training
        </div>
        <h1 className="text-4xl md:text-6xl font-bold text-white mb-6 font-outfit leading-tight">
          Community-Driven<br />
          <span className="text-[#F9D448]">Bias Training Data</span>
        </h1>
        <p className="text-xl text-white/80 max-w-3xl mx-auto mb-8">
          The first platform that captures authentic human reasoning from affected communities 
          to create training data that actually reduces AI bias.
        </p>
        <div className="flex flex-wrap justify-center gap-4">
          <Link to="/auth">
            <Button size="lg" className="bg-[#E8973E] hover:bg-[#E8973E]/90 text-white">
              Join the Movement <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
          <Link to="/synthetic-data-generator">
            <Button size="lg" variant="outline" className="border-white/30 text-white hover:bg-white/10">
              See It In Action
            </Button>
          </Link>
        </div>
      </section>

      {/* Problem Statement */}
      <section className="container mx-auto px-6 py-16">
        <div className="bg-white/5 backdrop-blur-sm rounded-3xl p-8 md:p-12 border border-white/10">
          <h2 className="text-2xl md:text-3xl font-bold text-white mb-6 text-center">
            The Problem With Current Approaches
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="text-center p-6">
              <div className="w-16 h-16 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-3xl">🤖</span>
              </div>
              <h3 className="text-white font-semibold mb-2">Algorithmic Generation</h3>
              <p className="text-white/60 text-sm">
                Most synthetic bias data is generated by AI itself—perpetuating the very biases it aims to fix.
              </p>
            </div>
            <div className="text-center p-6">
              <div className="w-16 h-16 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-3xl">🏢</span>
              </div>
              <h3 className="text-white font-semibold mb-2">Top-Down Assumptions</h3>
              <p className="text-white/60 text-sm">
                Tech companies define "bias" without consulting the communities actually affected by it.
              </p>
            </div>
            <div className="text-center p-6">
              <div className="w-16 h-16 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-3xl">📊</span>
              </div>
              <h3 className="text-white font-semibold mb-2">Lacking Lived Experience</h3>
              <p className="text-white/60 text-sm">
                Training data misses the nuance, context, and authentic reasoning that only real humans can provide.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Our Approach - TIR */}
      <section className="container mx-auto px-6 py-16">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            The Theory of Interrogative Reasoning
          </h2>
          <p className="text-white/70 max-w-2xl mx-auto">
            Our proprietary framework empowers communities to challenge AI outputs 
            through three powerful lenses.
          </p>
        </div>
        <div className="grid md:grid-cols-3 gap-6">
          <Card className="bg-gradient-to-br from-[#253B96] to-[#000860] border-[#E8973E]/30 overflow-hidden">
            <CardContent className="p-8">
              <div className="w-14 h-14 bg-[#E8973E] rounded-2xl flex items-center justify-center mb-6">
                <Users className="h-7 w-7 text-white" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Proximity</h3>
              <p className="text-white/70 text-sm leading-relaxed">
                Those closest to an issue have the deepest understanding. We center the voices 
                of people with direct lived experience to challenge assumptions.
              </p>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-[#253B96] to-[#000860] border-[#F9D448]/30 overflow-hidden">
            <CardContent className="p-8">
              <div className="w-14 h-14 bg-[#F9D448] rounded-2xl flex items-center justify-center mb-6">
                <Brain className="h-7 w-7 text-[#000860]" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Belief</h3>
              <p className="text-white/70 text-sm leading-relaxed">
                What assumptions underlie an AI's output? We help communities identify 
                hidden beliefs, deficit framing, and cultural misreadings.
              </p>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-[#253B96] to-[#000860] border-[#E8973E]/30 overflow-hidden">
            <CardContent className="p-8">
              <div className="w-14 h-14 bg-[#E8973E] rounded-2xl flex items-center justify-center mb-6">
                <GitBranch className="h-7 w-7 text-white" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Timing</h3>
              <p className="text-white/70 text-sm leading-relaxed">
                When does an intervention matter most? We capture the critical moments 
                where AI decisions can be redirected toward equity.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Dual Pipeline */}
      <section className="container mx-auto px-6 py-16">
        <div className="bg-gradient-to-r from-[#E8973E]/20 to-[#F9D448]/20 rounded-3xl p-8 md:p-12 border border-[#E8973E]/30">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                Dual Data Pipeline
              </h2>
              <p className="text-white/80 mb-6">
                We combine two powerful data sources to create the most comprehensive 
                anti-bias training datasets available.
              </p>
              <div className="space-y-4">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 bg-[#F9D448] rounded-lg flex items-center justify-center flex-shrink-0">
                    <Heart className="h-5 w-5 text-[#000860]" />
                  </div>
                  <div>
                    <h4 className="text-white font-semibold">Community Training Data</h4>
                    <p className="text-white/60 text-sm">
                      Real interrogations from consenting users—authentic human reasoning 
                      captured with full consent and anonymization.
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 bg-[#E8973E] rounded-lg flex items-center justify-center flex-shrink-0">
                    <Sparkles className="h-5 w-5 text-white" />
                  </div>
                  <div>
                    <h4 className="text-white font-semibold">TIR-Guided Synthetic Data</h4>
                    <p className="text-white/60 text-sm">
                      AI-generated examples following our TIR framework—diverse scenarios 
                      across domains, cultures, and bias types.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
              <div className="text-center mb-6">
                <div className="text-5xl font-bold text-[#F9D448]">2x</div>
                <div className="text-white/60 text-sm">More Effective Training</div>
              </div>
              <div className="space-y-3">
                <div className="flex items-center gap-3 text-white/80 text-sm">
                  <CheckCircle2 className="h-5 w-5 text-[#F9D448]" />
                  JSONL & CSV export formats
                </div>
                <div className="flex items-center gap-3 text-white/80 text-sm">
                  <CheckCircle2 className="h-5 w-5 text-[#F9D448]" />
                  Ready for LLM fine-tuning
                </div>
                <div className="flex items-center gap-3 text-white/80 text-sm">
                  <CheckCircle2 className="h-5 w-5 text-[#F9D448]" />
                  Harm type annotations included
                </div>
                <div className="flex items-center gap-3 text-white/80 text-sm">
                  <CheckCircle2 className="h-5 w-5 text-[#F9D448]" />
                  Affected group tracking
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Trust & Consent */}
      <section className="container mx-auto px-6 py-16">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Built on Trust & Consent
          </h2>
          <p className="text-white/70 max-w-2xl mx-auto">
            Community data sovereignty is non-negotiable. Every contribution is opt-in, 
            anonymized, and revocable.
          </p>
        </div>
        <div className="grid md:grid-cols-4 gap-4">
          {[
            { icon: Shield, label: "Opt-In Only", desc: "Explicit data contribution consent" },
            { icon: Users, label: "Anonymized", desc: "Identity protection guaranteed" },
            { icon: Heart, label: "Revocable", desc: "Withdraw consent anytime" },
            { icon: CheckCircle2, label: "Transparent", desc: "See exactly what's shared" },
          ].map((item, i) => (
            <div key={i} className="bg-white/5 rounded-xl p-6 text-center border border-white/10">
              <item.icon className="h-8 w-8 text-[#F9D448] mx-auto mb-3" />
              <h4 className="text-white font-semibold mb-1">{item.label}</h4>
              <p className="text-white/50 text-xs">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="container mx-auto px-6 py-20">
        <div className="text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Join the Movement
          </h2>
          <p className="text-white/70 max-w-xl mx-auto mb-8">
            Help build AI that truly serves everyone. Start facilitating sessions, 
            contribute to community training data, or explore our synthetic data tools.
          </p>
          <Link to="/auth">
            <Button size="lg" className="bg-[#F9D448] hover:bg-[#F9D448]/90 text-[#000860] font-semibold">
              Get Started Today <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="container mx-auto px-6 py-8 border-t border-white/10">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <img src={measureLogo} alt="MEASURE" className="h-8" />
            <span className="text-white/50 text-sm">© 2025 MEASURE. All rights reserved.</span>
          </div>
          <div className="flex items-center gap-6 text-white/50 text-sm">
            <Link to="/" className="hover:text-white transition-colors">Home</Link>
            <Link to="/dashboard" className="hover:text-white transition-colors">Dashboard</Link>
            <Link to="/synthetic-data-generator" className="hover:text-white transition-colors">Data Generator</Link>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default CommunityApproach;
